#!/bin/bash

# ================================================================
#  _______    _______     ____    _______    _______    __    ___
# |__   __|  |   ____|   / _  \  |__   __|  |   ____|  |  \   | |
#    | |     |  |__     | | | |     | |     |  |__     |   \  | |
#    | |     |   __|    | | | |     | |     |   __|    | |\ \ | |
#    | |     |  |___    | |_| |     | |     |  |___    | | \ \| |
#    |_|     |______|    \____/     |_|     |______|   |_|  \___|
# ----------------------------------------------------------------
# Author: Manuel Teodoro Tenango
# Email: teotenn@proton.me
# Repo: https://github.com/teotenn/dotfiles_wayland
# License: GPL-3
#
# My personal control script for audio and brightness
#
# Dependencies:
#  * amixer
#  * light
#  * mako - for notifications
#
# Usage:
#  Call `ttctl` followed by `-a/-b` for either audio or brightness
#    then `-u/-d` for either up/down an the percentage value to change
#
# Example to reduce Audio by 50 %
# `ttctl -a -d 50`
#
# ================================================================
mako &

wrarg() {
    echo "Wrong argument"
    exit 1
}

current_audio() {
    amixer get Master | awk '$0~/%/{print $5}' | tr -d '[]'
}

if [ "$1" != "" ]; then
    case $1 in
	-a | --audio)
	    if [ "$2" != "" ]; then
		case $2 in
		    -u | --up)
			amixer sset Master $3%+ && notify-send -c light "$(current_audio)"
			;;
		    -d | --down)
			amixer sset Master $3%- && notify-send -c light "$(current_audio)"
			;;
		    *)
			wrarg
			;;
		esac
	    fi
	    ;;
	-b | --brightness)
	    if [ "$2" != "" ]; then
		case $2 in
		    -u | --up)
			light -A $3 && notify-send -c light "  $(light -G)"
			;;
		    -d | --down)
			light -U $3 && notify-send -c light "  $(light -G)"
			;;
		    *)
			wrarg
			;;
		esac
	    fi
	    ;;
	*)
	    wrarg
	    ;;
    esac
fi
